### ISSUE TITLE
Short Search Logic Causing Missed Ads in Auto Refresh Service

### ISSUE THREAD

**Issue by marinoffDev** [H3llBunny/MobileBgWatch#1]
# Description:
The current logic in the short search functionality within the auto-refresh service has a flaw. The websites allows any user to modify their car ad post - when an edit is performed, this causes the ad's date to be updated to the current date instead of keeping the original one making it appear "bumped" above newly added ads. The current code logic stops processing once a match is found, which results in new ads not being added to the database.

# Steps to Reproduce
1. Post a new ad on Mobile.bg and note its position.
2. Modify an existing ad so that its date gets updated.
3. Run the scraper with the short search logic enabled.
4. Observe that the newly added ads are not being added to the database if a match is found with the updated ad.

# Expected Behavior
All new ads should be processed and added to the database, regardless of any matches with existing ads.

# Actual Behavior
New ads are skipped and not added to the database if the process encounters an ad that matches the criteria and stops.

# Proposed Solution

Change the sorting parameter in the query string from `sort=6` to `sort=7`.
- **Current Sort (sort=6):** Sorts ads by the most recently updated, which includes both new and edited ads.
- **Proposed Sort (sort=7):** Retrieves only ads posted within the last 48 hours. This ensures that the scraper fully scans recent ads, leading to fewer missed entries and reduced server requests when compared to the alternative (all).

This solution should help in reducing the number of requests made during the scraping process while ensuring no new ads are missed. It aligns better with the typical user expectation that all recent ads will be captured.

# Code Reference
I would start by looking into the logic within the `GetAllVehicleAdUrlsAsync` method in `ScraperService.cs`.

**Comment by H3llBunny** [comment]
2fdc8c4cb05173420e4acce2b3915e266a1cf2c0  Fixed, thanks!
